#DENTRO DO MYSQL WORKBENCH
#DROP TABLE PARA REMOVER O SCHEMA DA TABELA
#TRUNCADE TABLE APAGA APENAS AS INFORMAÇÕES DENTRO DELA

#REMOVE AS INFORMAÇÕES DA TABELA QUE ATENDAM A SEGUINTE CONDIÇÃO
DELETE FROM tabela WHERE condição;

DELETE FROM language WHERE language_id = 8;