#EXERCICIO 1
#Criando uma nova tabela
CREATE TABLE personagem 
(id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
nivel INT DEFAULT 1,
classe VARCHAR(50) NOT NULL
);
#EXERCICIO 2
CREATE TABLE filmes_antigos AS
SELECT * FROM film
WHERE last_update  BETWEEN '2006-01-01' AND '2006-30-12';
#EXERCICIO 3
CREATE TABLE log_acesso 
(log_id INT AUTO_INCREMENT PRIMARY KEY,
usuario VARCHAR(50) NOT NULL,
data_acesso TIMESTAMP DEFAULT CURRENT_TIMESTAMP);