
#SELECT FILTRA APENAS OS DADOS QUE VC QUER VER
#FROM REFERENCIA PARA UMA TABELA
SELECT actor_id,first_name FROM actor;
#COMANDO PARA MOSTRAR TODAS AS INFORMAÇÕES DA TABELA SEM FILTRO
SELECT * FROM actor;
