#USANDO O ORDER BY PARA ORDERNAR POR ORDEM ALFABETICA CRECENTE

SELECT actor_id,first_name 
FROM actor 
ORDER BY first_name ASC;
#USANDO O ORDER BY PARA ORDERNAR POR ORDEM ALFABETICA DECRECENTE
SELECT actor_id,first_name 
FROM actor 
ORDER BY first_name DESC;