USE sakila;
#USANDO O LIKE PARA ENCONTRAR TODOS QUE INICIAM COM A LETRA A
#NÃO IMPROTA SE É MAIUSCULO OU MINUSCULO
SELECT * FROM actor
WHERE first_name LIKE 'A%';

#USANDO O LIKE PRAR ENCONTRAR TODOS QUE FINALIZEM COM C
SELECT * FROM actor
WHERE first_name LIKE '%C';