USE carros;
#IMPORTANTE: SE ADICIONAR UMA COLONUA E RODAR O COMANDO CREATE ELE CRIA UMA COLUNA DO ZERO
#O RECOMENDAVEL É USAR O ALTER TABLE
CREATE TABLE marcas(
 id INT NOT NULL AUTO_INCREMENT,
 nome_marca VARCHAR(255) NOT NULL,
 origem VARCHAR(255) NOT NULL,
 PRIMARY KEY(id)
);
#atualizando colunads na tabela
ALTER TABLE marcas ADD origem VARCHAR(255);